name: doktasend-frontend
services:
  doktasend-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/dokta-team/doktasend-app:latest
    container_name: doktasend-app
    ports:
      - "3110:3110"  # Map port 3110 of the container to port 3110 on the host
    env_file:
      - .env.local
    # depends_on:
    #   - redis
    networks:
      - doktasend_network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # redis:
  #   image: "redis:latest"
  #   container_name: doktasend-redis
  #   ports:
  #     - "6379:6379"  # Default Redis port
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - doktasend_network
  #   restart: unless-stopped

# volumes:
#   redis-data:
   
networks:
  doktasend_network:
    driver: bridge