name: doktasend-frontend
services:
  doktasend-app:
    image: ghcr.io/dokta-team/doktasend-app:${API_VERSION}
    # container_name: doktasend-app
    ports:
      - "3110:3110"  # Map port 3110 of the container to port 3110 on the host
    env_file:
      - .env.local
    networks:
      - doktasend_network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
   
networks:
  doktasend_network:
    driver: bridge